version: '3.8'
services:
  db:
    image: postgres:17
    container_name: APP_DB_SENATI
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_network

volumes:
  pg_data:

networks:
  backend_network:
    driver: bridge